#!/usr/bin/env python

import argparse
import codecs
import logging
import sys

LOG = logging.getLogger(__name__)

def parse_args(argv):
    if argv is None:
        argv = sys.argv[1:]

    parser = argparse.ArgumentParser(description="")
    parser.add_argument('-l', '--log-level', default='INFO',
                        choices=['CRITICAL', 'ERROR', 'WARNING', 'INFO',
                        'DEBUG'])
    parser.add_argument('filenames',
                        metavar='FILE',
                        nargs='+',
                        help="input filenames")
    return parser.parse_args(argv)

def main(argv=None):
    options = parse_args(argv)
    logging.basicConfig(level=options.log_level,
                        format='%(asctime)-15s %(levelname)s: '
                        '[%(funcName)s@%(filename)s:%(lineno)d]: %(message)s')

    for filename in options.filenames:
        with codecs.open(filename, 'r', 'utf-8') as fh:
            for line in fh:
                LOG.info(line)

if __name__ == "__main__":
    sys.exit(main())
